routes/web.php
<?php

use Illuminate\Support\Facades\Route;

//::::::::::::::::::::::Rutas de Auth:::::::::::::::::::::::::::::::::://
Auth::routes();

//:::::::::::::::::::::::Middleware Para super admin::::::::::::::::::::::::://
Route::group(['as'=>'super.', 'prefix'=>'super','namespace'=>'Super','middleware'=>[
    'auth','super']], function(){        

//Dashboard superadmin vista
Route::get('dashboard','DashboardController@index')->name('dashboard');
//mantenimientos administradores
Route::resource('administradores','AdministradoresController');
//mantenimiento personas
Route::resource('personas','PersonasController');
//mantenimiento denuncias
Route::resource('denuncias','DenunciasController');
//ruta que sirve para exporta denuncia a pdf
Route::get('pdf-denuncia/{id}','DenunciasController@createPDF')->name('denuncia-pdf');
//mantenimiento denuncias pendientes
Route::resource('denuncias-pendientes','DenunciasPendientesController');
Route::Put('editar-pendientes/{id}','DenunciasPendientesController@updatedenuncias')->name('editar-pendientes');
Route::Put('editar-pendientes-documentos/{id}','DenunciasPendientesController@updatedocumentos')->name('editar-pendientes-documentos');
//mantenimiento denuncias seguimiento
Route::resource('denuncias-seguimiento','DenunciasSeguimientoController');
//mantenimiento denuncias completas
Route::resource('denuncias-completadas','DenunciasCompletadasController');
//mantenimiento denuncias finalizadas
Route::resource('denuncias-finalizadas','DenunciasFinalizadasController');
//mantenimiento denuncias baneadas
Route::resource('denuncias-baneadas','DenunciasBaneadasController');
//mantenimiento donantes
Route::resource('donantes', 'DonantesController');
//vista grafias datos generales
Route::get('datos_generales','RegistroController@general')->name('datos_generales');
Route::get('trans_general','DatosTransgeneros@general')->name('datos_generales_trans');
//vista graficas educacion
Route::get('educacion','RegistroController@educacion')->name('educacion');
Route::get('trans_estudios','DatosTransgeneros@educacion')->name('educacion_personas_trans');
//vista graficas acceso a la salud
Route::get('acesso_salud','RegistroController@salud')->name('acesso_salud');
Route::get('trans_salud','DatosTransgeneros@salud')->name('acceso_salud_trans');
//vista graficas trabajo u ocupacion
Route::get('trabajo_ocupacion','RegistroController@trabajo')->name('trabajo_ocupacion');
Route::get('trans_ocupacion', 'DatosTransgeneros@trabajo')->name('trabajo_ocupacion_trans');
//vista graficas acceso a la vivienda
Route::get('acceso_vivienda','RegistroController@vivienda')->name('acceso_vivienda');
Route::get('trans_vivienda','DatosTransgeneros@vivienda')->name('acceso_vivienda_trans');
//vista graficas politica y religion
Route::get('politica_religion','RegistroController@politica')->name('politica_religion');
Route::get('trans_religion','DatosTransgeneros@politica')->name('politica_religion_trans');
//vista graficas derechos
Route::get('derechos','RegistroController@derechos')->name('derechos');
Route::get('trans_derecho','DatosTransgeneros@derechos')->name('derechos_trans');
//mantnimiento para filtrar por año grafica
Route::post('general','RegistroController@general')->name('general');
//Filtro de ciudad por departamentos
Route::get('departamentos/{id}', 'FiltroDepartamentoController@Departament');

});

//:::::::::::::::::::::::Middleware Para admin::::::::::::::::::::::::://
Route::group(['as'=>'admin.', 'prefix'=>'admin','namespace'=>'Admin','middleware'=>[
    'auth','admin']], function(){

//Dashboard admin vista
Route::get('dashboard','DashboardController@index')->name('dashboard');
//mantenimiento personas
Route::resource('personas','PersonasController');
//mantenimiento denuncias
Route::resource('denuncias','DenunciasController');
//ruta que sirve para exporta denuncia a pdf
Route::get('pdf-denuncia/{id}','DenunciasController@createPDF')->name('denuncia-pdf');
//mantenimiento denuncias pendientes
Route::resource('denuncias-pendientes','DenunciasPendientesController');
Route::Put('editar-pendientes/{id}','DenunciasPendientesController@updatedenuncias')->name('editar-pendientes');
Route::Put('editar-pendientes-documentos/{id}','DenunciasPendientesController@updatedocumentos')->name('editar-pendientes-documentos');
//mantenimiento denuncias seguimiento
Route::resource('denuncias-seguimiento','DenunciasSeguimientoController');
Route::Put('editar-seguimiento/{id}','DenunciasSeguimientoController@updatedenuncias')->name('editar-seguimiento');
Route::Put('editar-seguimiento-documentos/{id}','DenunciasSeguimientoController@updatedocumentos')->name('editar-seguimiento-documentos');
//mantenimiento denuncias completas
Route::resource('denuncias-completadas','DenunciasCompletadasController');
//mantenimiento denuncias finalizadas
Route::resource('denuncias-finalizadas','DenunciasFinalizadasController');
//mantenimiento denuncias baneadas
Route::resource('denuncias-baneadas','DenunciasBaneadasController');
//mantenimiento donantes
Route::resource('donantes', 'DonantesController');
//vista grafias datos generales
Route::get('datos_generales','RegistroController@general')->name('datos_generales');
Route::get('trans_general','DatosTransgeneros@general')->name('datos_generales_trans');
//vista graficas educacion
Route::get('educacion','RegistroController@educacion')->name('educacion');
Route::get('trans_estudios','DatosTransgeneros@educacion')->name('educacion_personas_trans');
//vista graficas acceso a la salud
Route::get('acesso_salud','RegistroController@salud')->name('acesso_salud');
Route::get('trans_salud','DatosTransgeneros@salud')->name('acceso_salud_trans');
//vista graficas trabajo u ocupacion
Route::get('trabajo_ocupacion','RegistroController@trabajo')->name('trabajo_ocupacion');
Route::get('trans_ocupacion', 'DatosTransgeneros@trabajo')->name('trabajo_ocupacion_trans');
//vista graficas acceso a la vivienda
Route::get('acceso_vivienda','RegistroController@vivienda')->name('acceso_vivienda');
Route::get('trans_vivienda','DatosTransgeneros@vivienda')->name('acceso_vivienda_trans');
//vista graficas politica y religion
Route::get('politica_religion','RegistroController@politica')->name('politica_religion');
Route::get('trans_religion','DatosTransgeneros@politica')->name('politica_religion_trans');
//vista graficas derechos
Route::get('derechos','RegistroController@derechos')->name('derechos');
Route::get('trans_derecho','DatosTransgeneros@derechos')->name('derechos_trans');
//mantnimiento para filtrar por año grafica
Route::post('general','RegistroController@general')->name('general');
//Filtro de ciudad por departamentos
Route::get('departamentos/{id}', 'FiltroDepartamentoController@Departament');

});

//:::::::::::::::::::::::Middleware Para Donantes:::::::::::::::::::::::://
Route::group(['as'=>'donante.', 'prefix'=>'donante','namespace'=>'Donante','middleware'=>[
    'auth','donante']], function(){

//Dashboard donante vista
Route::get('dashboard','DashboardController@index')->name('dashboard');
//vista grafias datos generales
Route::get('datos_generales','RegistroController@general')->name('datos_generales');
//vista graficas educacion
Route::get('educacion','RegistroController@educacion')->name('educacion');
//vista graficas acceso a la salud
Route::get('acesso_salud','RegistroController@salud')->name('acesso_salud');
//vista graficas trabajo u ocupacion
Route::get('trabajo_ocupacion','RegistroController@trabajo')->name('trabajo_ocupacion');
//vista graficas acceso a la vivienda
Route::get('acceso_vivienda','RegistroController@vivienda')->name('acceso_vivienda');
//vista graficas politica y religion
Route::get('politica_religion','RegistroController@politica')->name('politica_religion');
//vista graficas derechos
Route::get('derechos','RegistroController@derechos')->name('derechos');
//mantnimiento para filtrar por año grafica
Route::post('general','RegistroController@general')->name('general');

});

//:::::::::::::::::::::::Middleware Para Usuarios:::::::::::::::::::::::://
Route::group(['as'=>'user.', 'prefix'=>'user','namespace'=>'User','middleware'=>[
    'auth','user']], function(){

//vista de inicio usuarios
Route::get('home', 'HomeController@index')->name('home');
//Filtro de ciudad por departamentos
Route::get('departamentos/{id}', 'FiltroDepartamentoController@Departament');
//Mantenimiento Denuncia
Route::post ('denuncias', 'DenunciasController@store')->name('denuncias');;


});

//::::::::::::::::::::::::::Middleware Sin Logeo::::::::::::::::::::::::::://
Route::group(['middleware' => ['guest']], function () {

Route::get('/', 'Frontend\HomeController@index')->name('home');
//Filtro de ciudad por departamentos
Route::get('departamentos/{id}', 'Frontend\FiltroDepartamentoController@Departament');
//Mantenimiento Registro
Route::post ('registro', 'Frontend\RegistroUsuariosController@store')->name('registro');;
//Login Usuarios
Route::post('user_login', 'Auth\UserLoginController@login')->name('user_login');

});

app/Http/Controllers/User/DenunciasController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Carbon\Carbon;
use App\Denuncias;
 
class DenunciasController extends Controller
{
    //Funcion para Agregar una denuncia
    public function store(Request $request)
    {
        $this->validate($request,[
            //Datos Generales//
            'fecha_del_suceso' => 'required|date',
            'fecha_cuando_se_reaizo_la_denuncia_formal' => 'date',
            'quien_registra_denuncia' => 'required',
            'breve_relato_del_hecho_consecuencias' => 'required',
            'foto_dui_frente' => 'max:5000|mimes:jpeg,jpg,png',
            'foto_dui_atras' => 'max:5000|mimes:jpeg,jpg,png',
            'foto_nit_frente' => 'max:5000|mimes:jpeg,jpg,png',
            'foto_nit_atras' => 'max:5000|mimes:jpeg,jpg,png',
            'foto_acta' => 'max:5000|mimes:jpeg,jpg,png',
            'foto_denuncia' => 'max:5000|mimes:jpeg,jpg,png',
            'foto_otro' => 'max:5000|mimes:jpeg,jpg,png',
            'foto_otro2' => 'max:5000|mimes:jpeg,jpg,png',
            'documento_dui' => 'mimes:pdf',
            'documento_nit' => 'mimes:pdf',
            'documento_acta' => 'mimes:pdf',
            'documento_denuncia' => 'mimes:pdf',
            'documento_otro' => 'mimes:pdf',
        ]);

        $denuncia = new Denuncias();
        //Datos Generales//
        $denuncia->user_id = Auth::user()->id;
        $denuncia->estado_de_la_denuncia = "Pendiente";
        $denuncia->fecha_del_suceso = Carbon::parse($request->fecha_del_suceso)->format('y-m-d');
        $denuncia->donde_ocurrio = $request->donde_ocurrio;
        $denuncia->quien_registra_denuncia = $request->quien_registra_denuncia;
        $denuncia->breve_relato_del_hecho_consecuencias = $request->breve_relato_del_hecho_consecuencias;
        $denuncia->tipo_principal_violacion_abuso = $request->tipo_principal_violacion_abuso;
        $denuncia->pais_id = 1;
        $denuncia->departamento_id = $request->departamento_id;
        $denuncia->ciudad_id = $request->ciudad_id;
        $denuncia->direccion_completa = $request->direccion_completa;
        $denuncia->tipo_secundario_violacion_abuso = $request->tipo_secundario_violacion_abuso;
        $denuncia->indique_cantidad_agresores = $request->indique_cantidad_agresores;
        $denuncia->forma_de_agrecion = $request->forma_de_agrecion;
        $denuncia->informacion_del_autor_del_hecho = $request->informacion_del_autor_del_hecho;
        $denuncia->realizo_una_denuncia_formal = $request->realizo_una_denuncia_formal;
        //Si la fecha viene como null
        if( $request->fecha_cuando_se_reaizo_la_denuncia_formal == NULL)
        {
        $denuncia->fecha_cuando_se_reaizo_la_denuncia_formal = NULL;
        }else{
        $denuncia->fecha_cuando_se_reaizo_la_denuncia_formal = Carbon::parse($request->fecha_cuando_se_reaizo_la_denuncia_formal)->format('y-m-d');
        }
        $denuncia->realizo_una_denuncia_formal = $request->realizo_una_denuncia_formal;
        $denuncia->documentacion_respaldatoria = $request->documentacion_respaldatoria;
        //dui frente
        $dui1=$request->file('foto_dui_frente');
        if (isset($dui1))
        {
        $currentDate1 = Carbon::now()->toDateString();
        $imagename1 = $currentDate1.'-'. uniqid() .'.'. $dui1->getClientOriginalName();
        $dui1->move('documentos/dui/',$imagename1);
        $denuncia->foto_dui_frente = $imagename1;
        }
        //dui atras
        $dui2=$request->file('foto_dui_atras');
        if (isset($dui2))
        {
        $currentDate2 = Carbon::now()->toDateString();
        $imagename2 = $currentDate2.'-'. uniqid() .'.'. $dui2->getClientOriginalName();
        $dui2->move('documentos/dui/',$imagename2);
        $denuncia->foto_dui_atras = $imagename2;
        }
        //dui documento
        $documentodui=$request->file('documento_dui');
        if (isset($documentodui))
        {
        $currentDate11 = Carbon::now()->toDateString();
        $imagename11 = $currentDate11.'-'. uniqid() .'.'. $documentodui->getClientOriginalName();
        $documentodui->move('documentos/dui/',$imagename11);
        $denuncia->documento_dui = $imagename11;
        }
        //nit frente
        $nit1=$request->file('foto_nit_frente');
        if (isset($nit1))
        {
        $currentDate3 = Carbon::now()->toDateString();
        $imagename3 = $currentDate3.'-'. uniqid() .'.'. $nit1->getClientOriginalName();
        $nit1->move('documentos/nit/',$imagename3);
        $denuncia->foto_nit_frente = $imagename3;
        }
        //nit atras
        $nit2=$request->file('foto_nit_atras');
        if (isset($nit2))
        {
        $currentDate4 = Carbon::now()->toDateString();
        $imagename4 = $currentDate4.'-'. uniqid() .'.'. $nit2->getClientOriginalName();
        $nit2->move('documentos/nit/',$imagename4);
        $denuncia->foto_nit_atras = $imagename4;
        }
        //nit documento
        $documentonit=$request->file('documento_nit');
        if (isset($documentonit))
        {
        $currentDate22 = Carbon::now()->toDateString();
        $imagename22 = $currentDate22.'-'. uniqid() .'.'. $documentonit->getClientOriginalName();
        $documentonit->move('documentos/nit/',$imagename22);
        $denuncia->documento_nit = $imagename22;
        }
        //acta
        $acta=$request->file('foto_acta');
        if (isset($acta))
        {
        $currentDate5 = Carbon::now()->toDateString();
        $imagename5 = $currentDate5.'-'. uniqid() .'.'. $acta->getClientOriginalName();
        $acta->move('documentos/acta_denuncia/',$imagename5);
        $denuncia->foto_acta = $imagename5;
        }
        //acta documento
        $documentoacta=$request->file('documento_acta');
        if (isset($documentoacta))
        {
        $currentDate33 = Carbon::now()->toDateString();
        $imagename33 = $currentDate33.'-'. uniqid() .'.'. $documentoacta->getClientOriginalName();
        $documentoacta->move('documentos/acta_denuncia/',$imagename33);
        $denuncia->documento_acta = $imagename33;
        }
        //denuncia
        $denuncias=$request->file('foto_denuncia');
        if (isset($denuncias))
        {
        $currentDate6 = Carbon::now()->toDateString();
        $imagename6 = $currentDate6.'-'. uniqid() .'.'. $denuncias->getClientOriginalName();
        $denuncias->move('documentos/acta_denuncia/',$imagename6);
        $denuncia->foto_denuncia = $imagename6;
        }
        //denuncia documento
        $documentodenuncia=$request->file('documento_denuncia');
        if (isset($documentodenuncia))
        {
        $currentDate44 = Carbon::now()->toDateString();
        $imagename44 = $currentDate33.'-'. uniqid() .'.'. $documentodenuncia->getClientOriginalName();
        $documentodenuncia->move('documentos/acta_denuncia/',$imagename33);
        $denuncia->documento_denuncia = $imagename44;
        }
        //Otros
        $otros=$request->file('foto_otro');
        if (isset($otros))
        {
        $currentDate7 = Carbon::now()->toDateString();
        $imagename7 = $currentDate7.'-'. uniqid() .'.'. $otros->getClientOriginalName();
        $otros->move('documentos/otros/',$imagename7);
        $denuncia->foto_otro = $imagename7;
        }
        //Otros 2
        $otros2=$request->file('foto_otro2');
        if (isset($otros2))
        {
        $currentDate8 = Carbon::now()->toDateString();
        $imagename8 = $currentDate8.'-'. uniqid() .'.'. $otros2->getClientOriginalName();
        $otros2->move('documentos/otros/',$imagename8);
        $denuncia->foto_otro2 = $imagename8;
        }
        //otro documento
        $documentootro=$request->file('documento_otro');
        if (isset($documentootro))
        { 
        $currentDate55 = Carbon::now()->toDateString();
        $imagename55 = $currentDate55.'-'. uniqid() .'.'. $documentootro->getClientOriginalName();
        $documentootro->move('documentos/otros/',$imagename55);
        $denuncia->documento_otro = $imagename55;
        }
        $denuncia->save();
        $subject = "Denuncia Aspidh";
        $for = Auth::user()->email;
        Mail::send('vendor.notifications.denuncias',compact('denuncia'),function($msj) use ($subject,$for)
            {
                $msj->from("no-reply@aspidh.org","ASPIDH");
                $msj->subject($subject);
                $msj->to("aspidh.arcoiris.trans@gmail.com","camila.aspidh@gmail.com");
                //$msj->to(["david.chavarria2@gmail.com","david.chavarria2@hotmail.com"]);
            });
        return redirect()->route('user.home')->with('denuncia', 'Denuncia realizada');
    }
}

resources/views/super/denuncias/pendientes/index.blade.php
@extends('super.partials.app')
@section('title','ASPIDH - Denuncias Pendientes')
@section('content')
<div class="content-wrapper">
    <!--========Navbar=========-->
    <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb bg-dark">
            <li class="breadcrumb-item"><a href="{{route('super.dashboard')}}">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Denuncias Pendientes</li>
        </ol>
    </nav>
    <div class="card">
        <div class="card-body cards">
            <div class="row grid-margin"> 
                <div class="col-12">
                    <div class="table-responsive">
                        <!--========tabla denuncias pendientes=========-->
                        <table id="example" class="table">
                            <thead>
                                <tr>
                                    <th hidden>¿Quien la realiza?</th>
                                    <th>Nombre</th>
                                    <th>Documento Identificacion</th>
                                    <th>Teléfono</th>
                                    <th hidden>Donde Ocurrio</th>
                                    <th hidden>Breve Relato</th>
                                    <th hidden>Tipo De Violencia</th>
                                    <th hidden>Tipo Secundario Violencia</th>
                                    <th hidden>Cantidad De Agresores</th>
                                    <th hidden>Forma Agresion</th>
                                    <th hidden>Informacion Del Autor</th>
                                    <th hidden>Realizo Denuncia Formal</th>
                                    <th hidden>Lugar Donde Realizo La Denuncia</th>
                                    <th>Fecha Del Suceso</th>
                                    <th hidden>Fecha Que Realizo La Denuncia</th>
                                    <th>Departamento</th>
                                    <th>Ciudad</th>
                                    <th hidden>Direccion</th>
                                    <th>Estado</th>
                                    <th hidden>Documento Respaldatorios</th>
                                    <th>Creado</th>
                                    <th>Actualizado</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($pendientes as $key=>$pendiente)
                                <tr>
                                    <td hidden>{{ $pendiente->quien_registra_denuncia }}</td>
                                    <td>{{ $pendiente->users->nombres_segun_dui }}
                                        {{ $pendiente->users->apellidos_segun_dui }}</td>
                                    <td>{{ $pendiente->users->documento_identificacion }}</td>
                                    <td>{{ $pendiente->users->numero_telefono }}</td>
                                    <td hidden>{{ $pendiente->donde_ocurrio }}</td>
                                    <td hidden>{{ $pendiente->breve_relato_del_hecho_consecuencias }}</td>
                                    <td hidden>{{ $pendiente->tipo_principal_violacion_abuso }}</td>
                                    <td hidden>{{ $pendiente->tipo_secundario_violacion_abuso }}</td>
                                    <td hidden>{{ $pendiente->indique_cantidad_agresores }}</td>
                                    <td hidden>{{ $pendiente->forma_de_agrecion }}</td>
                                    <td hidden>{{ $pendiente->informacion_del_autor_del_hecho }}</td>
                                    <td hidden>{{ $pendiente->realizo_una_denuncia_formal }}</td>
                                    <td hidden>{{ $pendiente->lugar_donde_realizo_la_denuncia_formal }}</td>
                                    <td>{{ date('d/m/Y',strtotime($pendiente->fecha_del_suceso)) }}</td>
                                    <td hidden>
                                        {{ date('d/m/Y',strtotime($pendiente->fecha_cuando_se_reaizo_la_denuncia_formal)) }}
                                    </td>
                                    <td>@if( isset($pendiente->departamentos->nombre_departamento) )
                                        {{ $pendiente->departamentos->nombre_departamento }} @endif</td>
                                    <td>@if( isset($pendiente->ciudades->nombre_ciudad) )
                                        {{ $pendiente->ciudades->nombre_ciudad }} @endif</td>
                                    <td hidden>{{ $pendiente->direccion_completa }}</td>
                                    <td>
                                        <div class="badge badge-danger badge-fw">{{ $pendiente->estado_de_la_denuncia }}
                                        </div>
                                    </td>
                                    <td hidden>{{ $pendiente->documentacion_respaldatoria }}</td>
                                    <td>{{ date('d/m/Y',strtotime($pendiente->created_at)) }}</td>
                                    <td>{{ date('d/m/Y',strtotime($pendiente->updated_at)) }}</td>
                                    <td>
                                        <!--========dropdown=========-->
                                        <div class="dropdown">
                                            <button class="btn btn-secondary dropdown-toggle" type="button"
                                                id="dropdownMenuButton4" data-toggle="dropdown" aria-haspopup="true"
                                                aria-expanded="false">
                                                <i class="icon-wrench"></i>
                                            </button>

                                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton4"
                                                x-placement="bottom-start"
                                                style="position: absolute; transform: translate3d(0px, 33px, 0px); top: -20px; left: 0px; will-change: transform;">
                                                <!--========Ver=========-->
                                                <a class="dropdown-item"
                                                    href="{{ URL::to('super/pdf-denuncia/'.$pendiente->id) }}">Ver</a>
                                                <!--========editar=========-->
                                                <a class="dropdown-item"
                                                    href="{{route('super.denuncias-pendientes.edit', $pendiente->id)}}">Editar</a>
                                                <!--========eliminar=========-->
                                                <a class="dropdown-item" href="javascript:void(0)"
                                                    onclick="deletedenunciapendiente({{$pendiente->id}})">Eliminar</a>
                                                <!--========cambiar estado=========-->
                                                <a class="dropdown-item" href="javascript:void(0)"
                                                    onclick="darleSeguimiento({{ $pendiente->id }})">Darle
                                                    Seguimiento</a>
                                                <!--========cambiar estado=========-->
                                                <a class="dropdown-item" onclick="banear({{ $pendiente->id }})"
                                                    href="javascript:void(0)">Banear
                                                    Denuncia</a>
                                            </div>
                                        </div>
                                        <!--========form cambiar estado=========-->
                                        <form id="denuncia-seguimiento-{{ $pendiente->id }}"
                                            action="{{ route('super.denuncias-pendientes.update',$pendiente->id) }}"
                                            method="POST" style="display: none;">
                                            @csrf
                                            @method('PUT')
                                        </form>
                                        <!--========form cambiar estado=========-->
                                        <form id="denuncia-baneada-{{ $pendiente->id }}"
                                            action="{{ route('super.denuncias-baneadas.update',$pendiente->id) }}"
                                            method="POST" style="display: none;">
                                            @csrf
                                            @method('PUT')
                                        </form>
                                        <!--========form eliminar=========-->
                                        <form id="denuncia-eliminada-pendiente-{{$pendiente->id}}"
                                            action="{{route('super.denuncias-pendientes.destroy',$pendiente->id)}}"
                                            method="POST" style="display: none;">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection