routes/web.php
<?php

use Illuminate\Support\Facades\Route;

//::::::::::::::::::::::Rutas de Auth:::::::::::::::::::::::::::::::::://
Auth::routes();

//:::::::::::::::::::::::Middleware Para super admin::::::::::::::::::::::::://
Route::group(['as'=>'super.', 'prefix'=>'super','namespace'=>'Super','middleware'=>[
    'auth','super']], function(){        

//Dashboard superadmin vista
Route::get('dashboard','DashboardController@index')->name('dashboard');
//mantenimientos administradores
Route::resource('administradores','AdministradoresController');
//mantenimiento personas
Route::resource('personas','PersonasController');
//mantenimiento denuncias
Route::resource('denuncias','DenunciasController');
//ruta que sirve para exporta denuncia a pdf
Route::get('pdf-denuncia/{id}','DenunciasController@createPDF')->name('denuncia-pdf');
//mantenimiento denuncias pendientes
Route::resource('denuncias-pendientes','DenunciasPendientesController');
Route::Put('editar-pendientes/{id}','DenunciasPendientesController@updatedenuncias')->name('editar-pendientes');
Route::Put('editar-pendientes-documentos/{id}','DenunciasPendientesController@updatedocumentos')->name('editar-pendientes-documentos');
//mantenimiento denuncias seguimiento
Route::resource('denuncias-seguimiento','DenunciasSeguimientoController');
//mantenimiento denuncias completas
Route::resource('denuncias-completadas','DenunciasCompletadasController');
//mantenimiento denuncias finalizadas
Route::resource('denuncias-finalizadas','DenunciasFinalizadasController');
//mantenimiento denuncias baneadas
Route::resource('denuncias-baneadas','DenunciasBaneadasController');
//mantenimiento donantes
Route::resource('donantes', 'DonantesController');
//vista grafias datos generales
Route::get('datos_generales','RegistroController@general')->name('datos_generales');
Route::get('trans_general','DatosTransgeneros@general')->name('datos_generales_trans');
//vista graficas educacion
Route::get('educacion','RegistroController@educacion')->name('educacion');
Route::get('trans_estudios','DatosTransgeneros@educacion')->name('educacion_personas_trans');
//vista graficas acceso a la salud
Route::get('acesso_salud','RegistroController@salud')->name('acesso_salud');
Route::get('trans_salud','DatosTransgeneros@salud')->name('acceso_salud_trans');
//vista graficas trabajo u ocupacion
Route::get('trabajo_ocupacion','RegistroController@trabajo')->name('trabajo_ocupacion');
Route::get('trans_ocupacion', 'DatosTransgeneros@trabajo')->name('trabajo_ocupacion_trans');
//vista graficas acceso a la vivienda
Route::get('acceso_vivienda','RegistroController@vivienda')->name('acceso_vivienda');
Route::get('trans_vivienda','DatosTransgeneros@vivienda')->name('acceso_vivienda_trans');
//vista graficas politica y religion
Route::get('politica_religion','RegistroController@politica')->name('politica_religion');
Route::get('trans_religion','DatosTransgeneros@politica')->name('politica_religion_trans');
//vista graficas derechos
Route::get('derechos','RegistroController@derechos')->name('derechos');
Route::get('trans_derecho','DatosTransgeneros@derechos')->name('derechos_trans');
//mantnimiento para filtrar por año grafica
Route::post('general','RegistroController@general')->name('general');
//Filtro de ciudad por departamentos
Route::get('departamentos/{id}', 'FiltroDepartamentoController@Departament');

});

//:::::::::::::::::::::::Middleware Para admin::::::::::::::::::::::::://
Route::group(['as'=>'admin.', 'prefix'=>'admin','namespace'=>'Admin','middleware'=>[
    'auth','admin']], function(){

//Dashboard admin vista
Route::get('dashboard','DashboardController@index')->name('dashboard');
//mantenimiento personas
Route::resource('personas','PersonasController');
//mantenimiento denuncias
Route::resource('denuncias','DenunciasController');
//ruta que sirve para exporta denuncia a pdf
Route::get('pdf-denuncia/{id}','DenunciasController@createPDF')->name('denuncia-pdf');
//mantenimiento denuncias pendientes
Route::resource('denuncias-pendientes','DenunciasPendientesController');
Route::Put('editar-pendientes/{id}','DenunciasPendientesController@updatedenuncias')->name('editar-pendientes');
Route::Put('editar-pendientes-documentos/{id}','DenunciasPendientesController@updatedocumentos')->name('editar-pendientes-documentos');
//mantenimiento denuncias seguimiento
Route::resource('denuncias-seguimiento','DenunciasSeguimientoController');
Route::Put('editar-seguimiento/{id}','DenunciasSeguimientoController@updatedenuncias')->name('editar-seguimiento');
Route::Put('editar-seguimiento-documentos/{id}','DenunciasSeguimientoController@updatedocumentos')->name('editar-seguimiento-documentos');
//mantenimiento denuncias completas
Route::resource('denuncias-completadas','DenunciasCompletadasController');
//mantenimiento denuncias finalizadas
Route::resource('denuncias-finalizadas','DenunciasFinalizadasController');
//mantenimiento denuncias baneadas
Route::resource('denuncias-baneadas','DenunciasBaneadasController');
//mantenimiento donantes
Route::resource('donantes', 'DonantesController');
//vista grafias datos generales
Route::get('datos_generales','RegistroController@general')->name('datos_generales');
Route::get('trans_general','DatosTransgeneros@general')->name('datos_generales_trans');
//vista graficas educacion
Route::get('educacion','RegistroController@educacion')->name('educacion');
Route::get('trans_estudios','DatosTransgeneros@educacion')->name('educacion_personas_trans');
//vista graficas acceso a la salud
Route::get('acesso_salud','RegistroController@salud')->name('acesso_salud');
Route::get('trans_salud','DatosTransgeneros@salud')->name('acceso_salud_trans');
//vista graficas trabajo u ocupacion
Route::get('trabajo_ocupacion','RegistroController@trabajo')->name('trabajo_ocupacion');
Route::get('trans_ocupacion', 'DatosTransgeneros@trabajo')->name('trabajo_ocupacion_trans');
//vista graficas acceso a la vivienda
Route::get('acceso_vivienda','RegistroController@vivienda')->name('acceso_vivienda');
Route::get('trans_vivienda','DatosTransgeneros@vivienda')->name('acceso_vivienda_trans');
//vista graficas politica y religion
Route::get('politica_religion','RegistroController@politica')->name('politica_religion');
Route::get('trans_religion','DatosTransgeneros@politica')->name('politica_religion_trans');
//vista graficas derechos
Route::get('derechos','RegistroController@derechos')->name('derechos');
Route::get('trans_derecho','DatosTransgeneros@derechos')->name('derechos_trans');
//mantnimiento para filtrar por año grafica
Route::post('general','RegistroController@general')->name('general');
//Filtro de ciudad por departamentos
Route::get('departamentos/{id}', 'FiltroDepartamentoController@Departament');

});

//:::::::::::::::::::::::Middleware Para Donantes:::::::::::::::::::::::://
Route::group(['as'=>'donante.', 'prefix'=>'donante','namespace'=>'Donante','middleware'=>[
    'auth','donante']], function(){

//Dashboard donante vista
Route::get('dashboard','DashboardController@index')->name('dashboard');
//vista grafias datos generales
Route::get('datos_generales','RegistroController@general')->name('datos_generales');
//vista graficas educacion
Route::get('educacion','RegistroController@educacion')->name('educacion');
//vista graficas acceso a la salud
Route::get('acesso_salud','RegistroController@salud')->name('acesso_salud');
//vista graficas trabajo u ocupacion
Route::get('trabajo_ocupacion','RegistroController@trabajo')->name('trabajo_ocupacion');
//vista graficas acceso a la vivienda
Route::get('acceso_vivienda','RegistroController@vivienda')->name('acceso_vivienda');
//vista graficas politica y religion
Route::get('politica_religion','RegistroController@politica')->name('politica_religion');
//vista graficas derechos
Route::get('derechos','RegistroController@derechos')->name('derechos');
//mantnimiento para filtrar por año grafica
Route::post('general','RegistroController@general')->name('general');

});

//:::::::::::::::::::::::Middleware Para Usuarios:::::::::::::::::::::::://
Route::group(['as'=>'user.', 'prefix'=>'user','namespace'=>'User','middleware'=>[
    'auth','user']], function(){

//vista de inicio usuarios
Route::get('home', 'HomeController@index')->name('home');
//Filtro de ciudad por departamentos
Route::get('departamentos/{id}', 'FiltroDepartamentoController@Departament');
//Mantenimiento Denuncia
Route::post ('denuncias', 'DenunciasController@store')->name('denuncias');;


});

//::::::::::::::::::::::::::Middleware Sin Logeo::::::::::::::::::::::::::://
Route::group(['middleware' => ['guest']], function () {

Route::get('/', 'Frontend\HomeController@index')->name('home');
//Filtro de ciudad por departamentos
Route::get('departamentos/{id}', 'Frontend\FiltroDepartamentoController@Departament');
//Mantenimiento Registro
Route::post ('registro', 'Frontend\RegistroUsuariosController@store')->name('registro');;
//Login Usuarios
Route::post('user_login', 'Auth\UserLoginController@login')->name('user_login');

});

app/Http/Controllers/Admin/DonantesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Brian2694\Toastr\Facades\Toastr;
use App\User;
use App\Denuncias;

class DonantesController extends Controller
{
    //Vista donantes
    public function index()
    {
        $donantes = User::where('role_id','4')->orderBy('created_at','desc')->get();
        $total_denuncias_pendientes = Denuncias::where('estado_de_la_denuncia','Pendiente')->count();
        return view('admin.donantes.index',compact('donantes','total_denuncias_pendientes'));
    }

    //Vista crear nuevo donante
    public function create()
    {
        $total_denuncias_pendientes = Denuncias::where('estado_de_la_denuncia','Pendiente')->count();
        return view('admin.donantes.create',compact('total_denuncias_pendientes'));
    }

    //Mantenimiento agregar nuevo donante
    public function store(Request $request)
    {
        $this->validate($request,[
            'nombres_segun_dui' => 'required|min:3|max:20',
            'apellidos_segun_dui' => 'required|min:3|max:20',
            'email' => 'required|unique:users',
            'password' => 'required|min:6',
        ]);
        $donantes = new User();
        $donantes->role_id = 4;
        $donantes->nombres_segun_dui = $request->nombres_segun_dui;
        $donantes->apellidos_segun_dui = $request->apellidos_segun_dui;
        $donantes->email = $request->email;
        $donantes->password = bcrypt($request->password);
        $donantes->contrasena = $request->password;
        $donantes->save();
        Toastr::success('Donante Creado Con Exito :)' ,'¡Felicidades!');
        return redirect()->route('admin.donantes.index');
    }

    //Vista editar donante
    public function edit($id)
    {
        $donantes = User::find($id);
        $total_denuncias_pendientes = Denuncias::where('estado_de_la_denuncia','Pendiente')->count();
        return view('admin.donantes.edit',compact('donantes','total_denuncias_pendientes'));
    }

    //Mantenimiento editar donante
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'nombres_segun_dui' => 'required|min:3|max:20',
            'apellidos_segun_dui' => 'required|min:3|max:20',
            'email' => 'required|unique:users,email,'.$id,
            'password' => 'required|min:6',
        ]);
        $donantes = User::find($id);
        $donantes->role_id = 4;
        $donantes->nombres_segun_dui = $request->nombres_segun_dui;
        $donantes->apellidos_segun_dui = $request->apellidos_segun_dui;
        $donantes->email = $request->email;
        $donantes->password = bcrypt($request->password);
        $donantes->contrasena = $request->password;
        $donantes->save();
        Toastr::warning('Donante Editado Con Exito :)' ,'¡Felicidades!');
        return redirect()->route('admin.donantes.index');
    }

    //Mantenimiento Eliminar donante
    public function destroy($id)
    {
        User::find($id)->delete();
        Toastr::error('Donante Eliminado Con Exito :)' ,'¡Felicidades!');
        return redirect()->back();
    }
}

app/Http/Controllers/Super/DonantesController.php
<?php

namespace App\Http\Controllers\Super;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\Mail;
use App\User;
use App\Denuncias;

class DonantesController extends Controller
{
    //Vista donantes
    public function index()
    {
        $donantes = User::where('role_id','4')->orderBy('created_at','desc')->get();
        $total_denuncias_pendientes = Denuncias::where('estado_de_la_denuncia','Pendiente')->count();
        return view('super.donantes.index',compact('donantes','total_denuncias_pendientes'));
    }

    //Vista crear nuevo donante
    public function create()
    {
        $total_denuncias_pendientes = Denuncias::where('estado_de_la_denuncia','Pendiente')->count();
        return view('super.donantes.create',compact('total_denuncias_pendientes'));
    }

    //Mantenimiento agregar nuevo donante
    public function store(Request $request)
    {
        $this->validate($request,[
            'nombres_segun_dui' => 'required|min:3|max:20',
            'apellidos_segun_dui' => 'required|min:3|max:20',
            'email' => 'required|unique:users',
            'password' => 'required|min:6',
        ]);
        $donantes = new User();
        $donantes->role_id = 4;
        $donantes->nombres_segun_dui = $request->nombres_segun_dui;
        $donantes->apellidos_segun_dui = $request->apellidos_segun_dui;
        $donantes->email = $request->email;
        $donantes->password = bcrypt($request->password);
        $donantes->contrasena = $request->password;
        $donantes->save();
        $subject = "Acceso a ASPIDH";
        Mail::send('vendor.notifications.emailnotificaciondonante',compact('donantes'),function($msj) use ($subject,$donantes)
            {
                $msj->from("aspidh.arcoiris.trans@gmail.com","ASPIDH");
                $msj->subject($subject);
                $msj->to($donantes->email);
                //$msj->to("aspidh.arcoiris.trans@gmail.com");
            });
        Toastr::success('Donante Creado Con Exito :)' ,'¡Felicidades!');
        return redirect()->route('super.donantes.index');
    }

    //Vista editar donante
    public function edit($id)
    {
        $donantes = User::find($id);
        $total_denuncias_pendientes = Denuncias::where('estado_de_la_denuncia','Pendiente')->count();
        return view('super.donantes.edit',compact('donantes','total_denuncias_pendientes'));
    }

    //Mantenimiento editar donante
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'nombres_segun_dui' => 'required|min:3|max:20',
            'apellidos_segun_dui' => 'required|min:3|max:20',
            'email' => 'required|unique:users,email,'.$id,
            'password' => 'required|min:6',
        ]);
        $donantes = User::find($id);
        $donantes->role_id = 4;
        $donantes->nombres_segun_dui = $request->nombres_segun_dui;
        $donantes->apellidos_segun_dui = $request->apellidos_segun_dui;
        $donantes->email = $request->email;
        $donantes->password = bcrypt($request->password);
        $donantes->contrasena = $request->password;
        $donantes->save();
        Toastr::warning('Donante Editado Con Exito :)' ,'¡Felicidades!');
        return redirect()->route('super.donantes.index');
    }

    //Mantenimiento Eliminar donante
    public function destroy($id)
    {
        User::find($id)->delete();
        Toastr::error('Donante Eliminado Con Exito :)' ,'¡Felicidades!');
        return redirect()->back();
    }
}

resources/views/donantes/registro/acceso_salud.blade.php
@extends('donantes.partials.app')
@section('title','ASPIDH - Acesso a la salud')
@section('content')
<div class="content-wrapper">
    <!--========Navbar=========-->
    <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb bg-dark">
            <li class="breadcrumb-item"><a href="{{route('donante.dashboard')}}">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Acceso a la salud</li>
        </ol>
    </nav>
    <div class="row">
        <!--======Afiliada al seguro social=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart11->container() !!}
                    </div>
                </div>
            </div>
        </div>
        <!--======servicios del seguro social=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart12->container() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <!--======tipos de servicios de salud=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart13->container() !!}
                    </div>
                </div>
            </div>
        </div>
        <!--======programa de salud gubernamenta=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart14->container() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--========Script de graficas=========-->
{!! $chart11->script() !!}
{!! $chart12->script() !!}
{!! $chart13->script() !!}
{!! $chart14->script() !!}
@endsection

resources/views/donantes/registro/acceso_vivienda.blade.php
@extends('donantes.partials.app')
@section('title','ASPIDH - Acceso a la vivienda')
@section('content')
<div class="content-wrapper">
    <!--========Navbar=========-->
    <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb bg-dark">
            <li class="breadcrumb-item"><a href="{{route('donante.dashboard')}}">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Acceso a la vivienda</li>
        </ol>
    </nav>
    <div class="row">
        <!--======tipo de vivienda=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart19->container() !!}
                    </div>
                </div>
            </div>
        </div>
        <!--======Con quien vive=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart20->container() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <!--======porcentaje financiero viviendal=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart21->container() !!}
                    </div>
                </div>
            </div>
        </div>
        <!--======credito para una vivienda=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart22->container() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <!--======credito para vivienda y recibieron respuesta=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart23->container() !!}
                    </div>
                </div>
            </div>
        </div>
        <!--======ayuda gubernamental de acceso a la vivienda=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart24->container() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--========script de graficas=========-->
{!! $chart19->script() !!}
{!! $chart20->script() !!}
{!! $chart21->script() !!}
{!! $chart22->script() !!}
{!! $chart23->script() !!}
{!! $chart24->script() !!}
@endsection

resources/views/donantes/registro/datos_generales.blade.php
@extends('donantes.partials.app')
@section('title','ASPIDH - Datos Generales')
@section('content')
<div class="content-wrapper">
    <!--========Navbar=========-->
    <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb bg-dark">
            <li class="breadcrumb-item"><a href="{{route('donante.dashboard')}}">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Datos generales</li>
        </ol>
    </nav>
    <div class="row">
        <!--======Genero=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart3->container() !!}
                    </div>
                </div>
            </div>
        </div>
        <!--======orientacion=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart4->container() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--======total de personas departamento=========-->
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart5->container() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--======total personas registradas por mes=========-->
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <form action="{{route('donante.general')}}" method="POST">
                        @csrf
                        <select name="anios" id="anos">
                            <option value="">Seleccione Año</option>
                            <option value="2020">2020</option>
                            <option value="2021">2021</option>
                            <option value="2022">2022</option>
                        </select>
                        <button>generar grafica</button>
                    </form>
                    <div class="card-body graficas">
                        {!! $chart6->container() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--========script de graficas=========-->
{!! $chart3->script() !!}
{!! $chart4->script() !!}
{!! $chart5->script() !!}
{!! $chart6->script() !!}
@endsection

resources/views/donantes/registro/derechos.blade.php
@extends('donantes.partials.app')
@section('title','ASPIDH - Vulneración de derechos')
@section('content')
<div class="content-wrapper">
    <!--========Navbar=========-->
    <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb bg-dark">
            <li class="breadcrumb-item"><a href="{{route('donante.dashboard')}}">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Vulneración de derechos</li>
        </ol>
    </nav>
    <div class="row">
        <!--======discriminacion centro de estudio=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart30->container() !!}
                    </div>
                </div>
            </div>
        </div>
        <!--======discriminacion en el trabajo=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart31->container() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <!--======discriminacion centro de salud=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart32->container() !!}
                    </div>
                </div>
            </div>
        </div>
        <!--======discriminacion de entidades=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart33->container() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <!--======sufrido algun tipo de agresion=========-->
        <div class="col-md-6 mx-auto">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart34->container() !!}
                    </div>
                </div>
            </div>
        </div>
        <!--======mecanismos de defensa de sus derechos=========-->
        <div class="col-md-6 mx-auto">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart35->container() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--========script de graficas=========-->
{!! $chart30->script() !!}
{!! $chart31->script() !!}
{!! $chart32->script() !!}
{!! $chart33->script() !!}
{!! $chart34->script() !!}
{!! $chart35->script() !!}
@endsection

resources/views/donantes/registro/educacion.blade.php
@extends('donantes.partials.app')
@section('title','ASPIDH - Educación')
@section('content')
<div class="content-wrapper">
    <!--========Navbar=========-->
    <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb bg-dark">
            <li class="breadcrumb-item"><a href="{{route('donante.dashboard')}}">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Educación</li>
        </ol>
    </nav>
    <div class="row">
        <!--======estudian actualmente=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart7->container() !!}
                    </div>
                </div>
            </div>
        </div>
        <!--======Aprobado grato de estudio=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart8->container() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <!--======centro de estudio primario=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart9->container() !!}
                    </div>
                </div>
            </div>
        </div>
        <!--======centro de estudio universitario=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart10->container() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--========script de graficas=========-->
{!! $chart7->script() !!}
{!! $chart8->script() !!}
{!! $chart9->script() !!}
{!! $chart10->script() !!}
@endsection

resources/views/donantes/registro/trabajo_ocupacion.blade.php
@extends('donantes.partials.app')
@section('title','ASPIDH - Acesso a la salud')
@section('content')
<div class="content-wrapper">
    <!--========Navbar=========-->
    <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb bg-dark">
            <li class="breadcrumb-item"><a href="{{route('donante.dashboard')}}">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Trabajo u ocupación</li>
        </ol>
    </nav>
    <div class="row">
        <!--======cuenta con empleo formal=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart15->container() !!}
                    </div>
                </div>
            </div>
        </div>
        <!--======sectores de trabajo=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart16->container() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <!--======negado por su orientacion sexual=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart17->container() !!}
                    </div>
                </div>
            </div>
        </div>
        <!--======programa de acceso al trabajo gubernamental=========-->
        <div class="col-md-6">
            <div class="table-responsive paddinggraficas">
                <div class="card">
                    <div class="card-body graficas">
                        {!! $chart18->container() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--========script de graficas=========-->
{!! $chart15->script() !!}
{!! $chart16->script() !!}
{!! $chart17->script() !!}
{!! $chart18->script() !!}
@endsection