routes/web.php
<?php

use Illuminate\Support\Facades\Route;

//::::::::::::::::::::::Rutas de Auth:::::::::::::::::::::::::::::::::://
Auth::routes();

//:::::::::::::::::::::::Middleware Para super admin::::::::::::::::::::::::://
Route::group(['as'=>'super.', 'prefix'=>'super','namespace'=>'Super','middleware'=>[
    'auth','super']], function(){        

//Dashboard superadmin vista
Route::get('dashboard','DashboardController@index')->name('dashboard');
//mantenimientos administradores
Route::resource('administradores','AdministradoresController');
//mantenimiento personas
Route::resource('personas','PersonasController');
//mantenimiento denuncias
Route::resource('denuncias','DenunciasController');
//ruta que sirve para exporta denuncia a pdf
Route::get('pdf-denuncia/{id}','DenunciasController@createPDF')->name('denuncia-pdf');
//mantenimiento denuncias pendientes
Route::resource('denuncias-pendientes','DenunciasPendientesController');
Route::Put('editar-pendientes/{id}','DenunciasPendientesController@updatedenuncias')->name('editar-pendientes');
Route::Put('editar-pendientes-documentos/{id}','DenunciasPendientesController@updatedocumentos')->name('editar-pendientes-documentos');
//mantenimiento denuncias seguimiento
Route::resource('denuncias-seguimiento','DenunciasSeguimientoController');
//mantenimiento denuncias completas
Route::resource('denuncias-completadas','DenunciasCompletadasController');
//mantenimiento denuncias finalizadas
Route::resource('denuncias-finalizadas','DenunciasFinalizadasController');
//mantenimiento denuncias baneadas
Route::resource('denuncias-baneadas','DenunciasBaneadasController');
//mantenimiento donantes
Route::resource('donantes', 'DonantesController');
//vista grafias datos generales
Route::get('datos_generales','RegistroController@general')->name('datos_generales');
Route::get('trans_general','DatosTransgeneros@general')->name('datos_generales_trans');
//vista graficas educacion
Route::get('educacion','RegistroController@educacion')->name('educacion');
Route::get('trans_estudios','DatosTransgeneros@educacion')->name('educacion_personas_trans');
//vista graficas acceso a la salud
Route::get('acesso_salud','RegistroController@salud')->name('acesso_salud');
Route::get('trans_salud','DatosTransgeneros@salud')->name('acceso_salud_trans');
//vista graficas trabajo u ocupacion
Route::get('trabajo_ocupacion','RegistroController@trabajo')->name('trabajo_ocupacion');
Route::get('trans_ocupacion', 'DatosTransgeneros@trabajo')->name('trabajo_ocupacion_trans');
//vista graficas acceso a la vivienda
Route::get('acceso_vivienda','RegistroController@vivienda')->name('acceso_vivienda');
Route::get('trans_vivienda','DatosTransgeneros@vivienda')->name('acceso_vivienda_trans');
//vista graficas politica y religion
Route::get('politica_religion','RegistroController@politica')->name('politica_religion');
Route::get('trans_religion','DatosTransgeneros@politica')->name('politica_religion_trans');
//vista graficas derechos
Route::get('derechos','RegistroController@derechos')->name('derechos');
Route::get('trans_derecho','DatosTransgeneros@derechos')->name('derechos_trans');
//mantnimiento para filtrar por año grafica
Route::post('general','RegistroController@general')->name('general');
//Filtro de ciudad por departamentos
Route::get('departamentos/{id}', 'FiltroDepartamentoController@Departament');

});

//:::::::::::::::::::::::Middleware Para admin::::::::::::::::::::::::://
Route::group(['as'=>'admin.', 'prefix'=>'admin','namespace'=>'Admin','middleware'=>[
    'auth','admin']], function(){

//Dashboard admin vista
Route::get('dashboard','DashboardController@index')->name('dashboard');
//mantenimiento personas
Route::resource('personas','PersonasController');
//mantenimiento denuncias
Route::resource('denuncias','DenunciasController');
//ruta que sirve para exporta denuncia a pdf
Route::get('pdf-denuncia/{id}','DenunciasController@createPDF')->name('denuncia-pdf');
//mantenimiento denuncias pendientes
Route::resource('denuncias-pendientes','DenunciasPendientesController');
Route::Put('editar-pendientes/{id}','DenunciasPendientesController@updatedenuncias')->name('editar-pendientes');
Route::Put('editar-pendientes-documentos/{id}','DenunciasPendientesController@updatedocumentos')->name('editar-pendientes-documentos');
//mantenimiento denuncias seguimiento
Route::resource('denuncias-seguimiento','DenunciasSeguimientoController');
Route::Put('editar-seguimiento/{id}','DenunciasSeguimientoController@updatedenuncias')->name('editar-seguimiento');
Route::Put('editar-seguimiento-documentos/{id}','DenunciasSeguimientoController@updatedocumentos')->name('editar-seguimiento-documentos');
//mantenimiento denuncias completas
Route::resource('denuncias-completadas','DenunciasCompletadasController');
//mantenimiento denuncias finalizadas
Route::resource('denuncias-finalizadas','DenunciasFinalizadasController');
//mantenimiento denuncias baneadas
Route::resource('denuncias-baneadas','DenunciasBaneadasController');
//mantenimiento donantes
Route::resource('donantes', 'DonantesController');
//vista grafias datos generales
Route::get('datos_generales','RegistroController@general')->name('datos_generales');
Route::get('trans_general','DatosTransgeneros@general')->name('datos_generales_trans');
//vista graficas educacion
Route::get('educacion','RegistroController@educacion')->name('educacion');
Route::get('trans_estudios','DatosTransgeneros@educacion')->name('educacion_personas_trans');
//vista graficas acceso a la salud
Route::get('acesso_salud','RegistroController@salud')->name('acesso_salud');
Route::get('trans_salud','DatosTransgeneros@salud')->name('acceso_salud_trans');
//vista graficas trabajo u ocupacion
Route::get('trabajo_ocupacion','RegistroController@trabajo')->name('trabajo_ocupacion');
Route::get('trans_ocupacion', 'DatosTransgeneros@trabajo')->name('trabajo_ocupacion_trans');
//vista graficas acceso a la vivienda
Route::get('acceso_vivienda','RegistroController@vivienda')->name('acceso_vivienda');
Route::get('trans_vivienda','DatosTransgeneros@vivienda')->name('acceso_vivienda_trans');
//vista graficas politica y religion
Route::get('politica_religion','RegistroController@politica')->name('politica_religion');
Route::get('trans_religion','DatosTransgeneros@politica')->name('politica_religion_trans');
//vista graficas derechos
Route::get('derechos','RegistroController@derechos')->name('derechos');
Route::get('trans_derecho','DatosTransgeneros@derechos')->name('derechos_trans');
//mantnimiento para filtrar por año grafica
Route::post('general','RegistroController@general')->name('general');
//Filtro de ciudad por departamentos
Route::get('departamentos/{id}', 'FiltroDepartamentoController@Departament');

});

//:::::::::::::::::::::::Middleware Para Donantes:::::::::::::::::::::::://
Route::group(['as'=>'donante.', 'prefix'=>'donante','namespace'=>'Donante','middleware'=>[
    'auth','donante']], function(){

//Dashboard donante vista
Route::get('dashboard','DashboardController@index')->name('dashboard');
//vista grafias datos generales
Route::get('datos_generales','RegistroController@general')->name('datos_generales');
//vista graficas educacion
Route::get('educacion','RegistroController@educacion')->name('educacion');
//vista graficas acceso a la salud
Route::get('acesso_salud','RegistroController@salud')->name('acesso_salud');
//vista graficas trabajo u ocupacion
Route::get('trabajo_ocupacion','RegistroController@trabajo')->name('trabajo_ocupacion');
//vista graficas acceso a la vivienda
Route::get('acceso_vivienda','RegistroController@vivienda')->name('acceso_vivienda');
//vista graficas politica y religion
Route::get('politica_religion','RegistroController@politica')->name('politica_religion');
//vista graficas derechos
Route::get('derechos','RegistroController@derechos')->name('derechos');
//mantnimiento para filtrar por año grafica
Route::post('general','RegistroController@general')->name('general');

});

//:::::::::::::::::::::::Middleware Para Usuarios:::::::::::::::::::::::://
Route::group(['as'=>'user.', 'prefix'=>'user','namespace'=>'User','middleware'=>[
    'auth','user']], function(){

//vista de inicio usuarios
Route::get('home', 'HomeController@index')->name('home');
//Filtro de ciudad por departamentos
Route::get('departamentos/{id}', 'FiltroDepartamentoController@Departament');
//Mantenimiento Denuncia
Route::post ('denuncias', 'DenunciasController@store')->name('denuncias');;


});

//::::::::::::::::::::::::::Middleware Sin Logeo::::::::::::::::::::::::::://
Route::group(['middleware' => ['guest']], function () {

Route::get('/', 'Frontend\HomeController@index')->name('home');
//Filtro de ciudad por departamentos
Route::get('departamentos/{id}', 'Frontend\FiltroDepartamentoController@Departament');
//Mantenimiento Registro
Route::post ('registro', 'Frontend\RegistroUsuariosController@store')->name('registro');;
//Login Usuarios
Route::post('user_login', 'Auth\UserLoginController@login')->name('user_login');

});

resources/views/admin/partials/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!--Informacion encabezado-->
    <link rel="icon" type="image/png" href="{{asset('admin/img/icono.ico')}}">
    <title>@yield('title')</title>
    <!--diseno-->
    <link href="{{asset('admin/css/style.css')}}" type="text/css" rel="stylesheet">
    <!--icons-->
    <link href="{{asset('admin/css/simple-line-icons/css/simple-line-icons.css')}}" type="text/css" rel="stylesheet">
    <!--toastr-->
    <link href="{{asset('admin/css/toastr.min.css')}}" type="text/css" rel="stylesheet">
    <!--datatable-->
    <link href="{{asset('admin/css/datatable/dataTables.bootstrap4.css')}}" type="text/css" rel="stylesheet">
    <!--Select2-->
    <link href="{{asset('admin/css/select2.min.css')}}" type="text/css" rel="stylesheet">
    <!--dropify-->
    <link href="{{asset('admin/css/dropify.min.css')}}" type="text/css" rel="stylesheet">
    <!--Datepickert-->
    <link rel="stylesheet" href="{{asset('admin/css/bootstrap-datetimepicker.min.css')}}">

</head>

<body>

    <!--Carga de pagina-->
    <div id="preloader">
        <div class="loader" id="loader-1"></div>
    </div>

    <!--Plantilla-->
    <div class="container-scroller">
        @include('admin.partials.navbar')
        <div class="container-fluid page-body-wrapper">
            <div class="row row-offcanvas row-offcanvas-right">
                @include('admin.partials.sidebar')
                @yield('content')
                @include('admin.partials.footer')
            </div>
        </div>
    </div>

    <!--jquery -->
    <script src="{{asset('admin/js/jquery.min.js')}}"></script>
    <!--toastr-->
    <script src="{{asset('admin/js/toastr.min.js')}}"></script>
    {!! Toastr::message() !!}
    <!--bundle-->
    <script src="{{asset('admin/js/vendor.bundle.base.js')}}"></script>
    <!--navbar mobile-->
    <script src="{{asset('admin/js/off-canvas.js')}}"></script>
    <!--menu collapse-->
    <script src="{{asset('admin/js/misc.js')}}"></script>
    <!--Script para select2-->
    <script src="{{asset('admin/js/select2.full.min.js')}}"></script>
    <!--Graficas-->
    <script src="{{asset('admin/js/highcharts.js')}}"></script>
    <script src="{{asset('admin/js/exporting.js')}}"></script>
    <script src="{{asset('admin/js/export-data.js')}}"></script>
    <script src="{{asset('admin/js/offline-exporting.js')}}"></script>
    <!--Script sweetalert-->
    <script src="{{asset('admin/js/sweetalert2@9.js')}}"></script>
    <!--Scrit para datatable-->
    <script src="{{asset('admin/js/datatable/jquery.dataTables.js')}}"></script>
    <script src="{{asset('admin/js/datatable/dataTables.bootstrap4.js')}}"></script>
    <script src="{{asset('admin/js/datatable/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('admin/js/datatable/buttons.bootstrap4.min.js')}}"></script>
    <script src="{{asset('admin/js/datatable/jszip.min.js')}}"></script>
    <script src="{{asset('admin/js/datatable/buttons.html5.min.js')}}"></script>
    <!--Datepickert-->
    <script src="{{asset('admin/js/moment-with-locales.min.js')}}"></script>
    <script>
    moment.locale('es');
    </script>
    <script src="{{asset('admin/js/bootstrap-datetimepicker.min.js')}}"></script>
    <!--dropify-->
    <script src="{{asset('admin/js/dropify.min.js')}}"></script>
    <!--Scrit para mantenimientos-->
    <script src="{{asset('admin/js/mantenimientos.js')}}"></script>
    <!--Script Funcionalidades-->
    <script src="{{asset('admin/js/script.js')}}"></script>
    <!--Script Formulario Denuncias-->
    <script src="{{asset('admin/js/formulario_denuncia.js')}}"></script>
    <!--Script Formulario registro-->
    <script src="{{asset('admin/js/formulario_registro.js')}}"></script>
    <!--Script para validar input-->
    <script src="{{asset('admin/js/jquery.mask.js')}}"></script>
    <!--Modal de Denuncias-->
    @include('admin.denuncias.denuncia.modal')
    <!--=======Errores de formulario==========-->
    @if ($errors->all())
    <script src="{{asset('admin/js/error.js')}}"></script>
    @endif

</body>

</html>

resources/views/admin/partials/footer.blade.php
<!--==========footer==========-->
<footer class="footer">
    <div class="container-fluid clearfix">
        <center><span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2020
                <a href="https://aspidhsv.org/" target="_blank">Aspidh</a>. All rights reserved.</span></center>
    </div>
</footer>

resources/views/admin/partials/navbar.blade.php
<!--============Logo o Nombre==============-->
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">
        <a class="navbar-brand brand-logo" href="{{route('admin.dashboard')}}">ASPIDH</a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center">
        <!--============Boton de nueva denuncia==============-->
        <ul class="navbar-nav">
            <li class="nav-item dropdown d-lg-flex">
                <a class="nav-link dropdown-toggle nav-btn" href="#" data-toggle="modal" data-target="#exampleModal">
                    <span class="btn">+ Nueva Denuncia</span>
                </a>
            </li>
        </ul>
        <!--=====boton menu mobile=======-->
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
            data-toggle="offcanvas">
            <span class="icon-menu"></span>
        </button>
    </div>
</nav>

resources/views/admin/partials/sidebar.blade.php
<!---=============Opciones de menu lateral==============-->
<div id="right-sidebar" class="settings-panel">
    <div class="tab-content" id="setting-content">
        <div class="tab-pane fade show active scroll-wrapper" role="tabpanel" aria-labelledby="todo-section">
        </div>
    </div>
</div>
<!---=============Menu==============-->
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <div class="nav-link">
                <!--========img=========-->
                <div class="profile-image">
                    <img src="{{asset('admin/img/logo.png')}}">
                    <span class="online-status online"></span>
                </div>
            </div>
            <hr>
        </li>
        <!---===dashboard======-->
        <li class="nav-item">
            <a class="nav-link" href="{{route('admin.dashboard')}}">
                <i class="icon-rocket menu-icon"></i>
                <span class="menu-title">Dashboard</span>
            </a>
        </li>
        <!---===Donantes======-->
        <li class="nav-item">
            <a class="nav-link" href="{{ route('admin.donantes.index') }}">
                <i class="icon-heart menu-icon"></i>
                <span class="menu-title">Donantes</span>
            </a>
        </li>
        <!---===Personas registradas======-->
        <li class="nav-item">
            <a class="nav-link" href="{{ route('admin.personas.index') }}">
                <i class="icon-user menu-icon"></i>
                <span class="menu-title">Personas Registradas</span>
            </a>
        </li>
        <!---===Denuncias======-->
        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#page-layouts" aria-expanded="false"
                aria-controls="page-layouts">
                <i class="icon-docs menu-icon"></i>
                <span class="menu-title">Denuncias</span>
                <span class="badge badge-danger" title="Denuncias Pendientes">{{ $total_denuncias_pendientes }}</span>
            </a>
            <div class="collapse" id="page-layouts">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"><a class="nav-link"
                            href="{{ route('admin.denuncias-pendientes.index') }}">Denuncias Pendientes</a></li>
                    <li class="nav-item"><a class="nav-link"
                            href="{{ route('admin.denuncias-seguimiento.index') }}">Denuncias Seguimiento</a></li>
                    <li class="nav-item"><a class="nav-link"
                            href="{{ route('admin.denuncias-completadas.index') }}">Denuncias Completadas</a></li>
                    <li class="nav-item"><a class="nav-link"
                            href="{{ route('admin.denuncias-finalizadas.index') }}">Denuncias Finalizadas</a></li>
                    <li class="nav-item"> <a class="nav-link"
                            href="{{ route('admin.denuncias-baneadas.index') }}">Denuncias Baneadas</a></li>
                </ul>
            </div>
        </li>
        <!---===Graficas registro======-->
        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#sidebar-layouts" aria-expanded="false"
                aria-controls="sidebar-layouts">
                <i class="icon-chart menu-icon"></i>
                <span class="menu-title">Graficas Registro</span>
            </a>
            <div class="collapse" id="sidebar-layouts">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"><a class="nav-link" href="{{route('admin.datos_generales')}}">Datos
                            generales</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{route('admin.educacion')}}">Educación</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{route('admin.acesso_salud')}}">Acesso a la
                            salud</a></li>
                    <li class="nav-item"> <a class="nav-link" href="{{route('admin.trabajo_ocupacion')}}">Trabajo u
                            ocupación</a></li>
                    <li class="nav-item"> <a class="nav-link" href="{{route('admin.acceso_vivienda')}}">Acceso a la
                            vivienda</a></li>
                    <li class="nav-item"> <a class="nav-link" href="{{route('admin.politica_religion')}}">política y
                            religión</a></li>
                    <li class="nav-item"> <a class="nav-link" href="{{route('admin.derechos')}}">Vulneración de
                            derechos</a></li>
                </ul>
            </div>
        </li>
        <!---===Graficas registro personas trans======-->
        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#sidebar-layouts" aria-expanded="false"
                aria-controls="sidebar-layouts">
                <i class="icon-chart menu-icon"></i>
                <span class="menu-title">Graficas mujer transexual</span>
            </a>
            <div class="collapse" id="sidebar-layouts">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"><a class="nav-link" href="{{route('admin.datos_generales_trans')}}">Datos
                            generales</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{route('admin.educacion_personas_trans')}}">Educación</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{route('admin.acceso_salud_trans')}}">Acesso a la
                            salud</a></li>
                    <li class="nav-item"> <a class="nav-link" href="{{route('admin.trabajo_ocupacion_trans')}}">Trabajo u
                            ocupación</a></li>
                    <li class="nav-item"> <a class="nav-link" href="{{route('admin.acceso_vivienda_trans')}}">Acceso a la
                            vivienda</a></li>
                    <li class="nav-item"> <a class="nav-link" href="{{route('admin.politica_religion_trans')}}">política y
                            religión</a></li>
                    <li class="nav-item"> <a class="nav-link" href="{{route('admin.derechos_trans')}}">Vulneración de
                            derechos</a></li>
                </ul>
            </div>
        </li>
        <hr>
        <!---===Cerrar Sesion======-->
        <li class="nav-item nav-doc">
            <a class="nav-link bg-primary" href="{{ route('logout')  }}"
                onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                <i class="icon-power menu-icon"></i>
                <span class="menu-title">Cerrar sesión</span>
            </a>
            <!--=====form sesion=======-->
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </li>
    </ul>
</nav>